plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/NumericPredicate:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']
